### ISSUE TITLE
穿鑽裝的泡芙有時看起來很奇怪

### ISSUE THREAD

**Issue by Sculkman** [waltsai/colorful_puff#1]
![unknown](https://user-images.githubusercontent.com/101435618/158062554-f3eaab89-b403-4582-9da9-613b35a474de.png)

**Comment by waltsai** [comment]
![2022-03-23_17 59 29](https://user-images.githubusercontent.com/42564593/159673890-f9346a25-1d3e-4f0e-b14e-d3d2330c0784.png)
修好拉
